AllCops:
  Exclude:
    - 'test/dummy/script/**/*'
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Max: 24.02 # TODO: Lower to 15
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 9 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 24

Metrics/ModuleLength:
  Max: 122 # TODO: Lower to 100

Metrics/ParameterLists:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9 # TODO: Lower to 7

Rails:
  Enabled: true

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  AllowForAlignment:
    - '='
    - '=>'
    - '||='

Style/UnneededPercentQ:
  Exclude:
    - 'route_translator.gemspec'
